server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/consultorio
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
