server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/consultorio
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
